### ISSUE TITLE
Two-way data binding AndroidX issue

### ISSUE THREAD

**Issue by RhysXibis** [braintree/braintree-android-drop-in#105]
I am unable to build a project when using AndroidX , two-way data binding and Braintree's drop in UI library. To be clear, the project builds fine when just observing the data as opposed to two-way binding. 

I have created a sample project which can be found at the following link: https://github.com/RhysXibis/Braintree-two-way-data-binding-issue

Please note that to achieve two-way binding I add an equals symbol on line 31 in the activity_main.xml file.

**Comment by quinnjn** [comment]
I wanted to start with a huge thank you for posting a demo of the issue ❤️ ❤️ ❤️ . It makes debugging issues so much easier, and increases turn around time to a solve. Thank you very much!

This issue is not isolated to Braintree, it is an issue with the gradle build tools. Another Braintree merchant had posted an issue to Google around this: https://issuetracker.google.com/issues/117544947

The issue has been fixed and will be available in Gradle Build Tools 3.3 (currently in beta4 at the time of this comment).

We at Braintree do not use data binding, but our Visa Checkout SDK dependency does. This gets passed through to Drop-in. An easy fix is to `exclude: 'visa-checkout'` from the Drop-in dependency. 

I'll post a PR to your demo on what you should do to solve the 2-way data binding issue.
