### ISSUE TITLE
Its not a issue but the Question, How to open custom webview on paypal click 

### ISSUE THREAD

**Issue by radhikapooniya2** [braintree/braintree-android-drop-in#124]
Hello All,

I want to change PayPal click method When we click on "Add Payment Method",
I want to open custom WebView on PayPal click, is it possible to change this from braintree internal library methods, because it is not showing that PayPal click in Braintree main activity

After your suggestion in issue #121, I contact to PayPal support they suggest to use prototype with a WebView in Android. Here is suggested code :-

CookieManager cm = CookieManager.getInstance();

cm.removeAllCookies(new ValueCallback<Boolean>() {

@Override

public void onReceiveValue(Boolean value) {

// ...

}

});

this.myWebView = (WebView) findViewById(R.id.sampleWebView);

this.myWebView.setWebViewClient(new WebViewClient() {

@Override

public boolean shouldOverrideUrlLoading(WebView view, String url) {

// Check new URL; if it's the return or cancel URL, close web view and move on

Log.d("shouldOverrideUrlLoading", url);

return false;

}

@Override

public void onPageFinished(WebView view, String url) {

super.onPageFinished(view, url);

// Check if the URL is the return or cancel URL; close web view and move on

Log.d("onPageFinished", url);
}

});

this.myWebView.getSettings().setJavaScriptEnabled(true);

this.myWebView.loadUrl("https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0WL203871T523084M");

I try on my way but not able to do it on PayPal click when popup is coming from bottom on "add payment method" click.
It will be more helpful if you can provide us updated library with above suggested code by PayPal or please suggest some other way.

**Comment by quinnjn** [comment]
Hi @radhikapooniya2,

I'm a little confused on what you're trying to accomplish so I'm going to list a couple things and hopefully this helps.

- PayPal security states that PayPal web pages cannot be displayed in a `WebView` and must use either a SDK that handles the PayPal via the mobile browser, or Chrome Custom Tabs.

  https://developer.paypal.com/docs/classic/lifecycle/info-security-guidelines/#do-not-use-a-webview-to-display-paypal-web-pages-within-your-application

- > because it is not showing that PayPal click in Braintree main activity

  Braintree doesn't have a main Activity. Are you not getting a result from the Chrome Custom Tab? If so it sounds like you haven't declared a URL scheme in your AndroidManifest. Step 3 on this page: [Client Side integration guide for PayPal via Braintree Android](https://developers.braintreepayments.com/guides/paypal/client-side/android/v3)

If you're trying to just process PayPal via Braintree, all the steps to process PayPal are listed in the the [Client Side integration guide for PayPal via Braintree Android](https://developers.braintreepayments.com/guides/paypal/client-side/android/v3).
