### ISSUE TITLE
How to recover for app crash during browser PayPal setup flow?

### ISSUE THREAD

**Issue by LaVielle** [braintree/braintree-android-drop-in#230]
### General information

* SDK/Library version: Tbh I'm not sure. I'm using https://github.com/wgltony/react-native-braintree-dropin-ui, which has `implementation 'com.braintreepayments.api:drop-in:4.+'` as a dependency in `build.gradle`.
* Environment: Both Sandbox and Production
* Android Version and Device: Mostly low end devices such as Redmi 9A (running Android 10), but any device if the user quit the app manually.

### Issue description

In some cases the app crashes unexpectedly while the user is midway through the PayPal setup flow in the browser app. This is probably not a bug in this library. It happens sporadically, mostly on low end devices. **Only on Android.**
It becomes a problem when the setup completes and the user is sent back to the app: the app context is gone and we cannot handle PayPal success correctly (eg. send the nonce to our backend).
I have a React Native app and as mentioned above, I am using react-native-braintree-dropin-ui. That library is essentially a wrapper around `braintree-android-drop-in` so I think it's still relevant to post the issue here.

So my questions are:
- is there a way to recover from such an app crash during the browser setup flow?
- is there a way to store the nonce in some sort of local storage (eg. Shared Preferences) when the browser flow succeeds, and to retrieve it on app start?
- is there a way to configure a success deeplink that is opened when the browser flow succeeds (eg. https://myapp.co/?braintrenonce=xxxxxx), in which case my app could handle the deeplink no matter whether it's in background or quit state.

Thanks!

**Comment by scannillo** [comment]
Hi @LaVielle thanks for opening this issue. 

Our SDK supports Android 21+, so we aren't going to provide fixes / support for issues on devices running Android 10. For that reason, I am going to close this issue. Please see our [Client SDK Deprecation policy](https://developers.braintreepayments.com/guides/client-sdk/deprecation-policy/android/v3#platform-support) to read about our supported versions.
 
> is there a way to recover from such an app crash during the browser setup flow?

I don't know enough about where exactly your application is crashing in order to provide tips on how to safeguard for it. We would need more specifics on where in the `braintree_android` implementation you are able to replicate this crash.

> is there a way to store the nonce in some sort of local storage (eg. Shared Preferences) when the browser flow succeeds, and to retrieve it on app start?

Since [nonces do expire in 3 hours](https://developers.braintreepayments.com/guides/payment-method-nonces#lifespan), I don't think this is ideal. You _could_ do something like this on your own, but it will likely confuse a user if their app crashes during checkout but you continue on to transact with their nonce.

> is there a way to configure a success deeplink that is opened when the browser flow succeeds (eg. https://myapp.co/?braintrenonce=xxxxxx), in which case my app could handle the deeplink no matter whether it's in background or quit state.

For our checkout flows that utilize a browser switch (such as PayPal) you must [define a URL scheme](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v3#paypal). [See docs](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3#browser-switch-setup).
