### ISSUE TITLE
Support version 4.x of the core SDK

### ISSUE THREAD

**Issue by fondesa** [braintree/braintree-android-drop-in#250]
### General information

* Core SDK version: 4.2.0
* Drop-in SDK version:  5.2.1

### Issue description

We started the update to the version **4.2.0** of the core SDK.
Unfortunately, the drop-in SDK still depends from the core version **3.x**. 
This makes impossible the update of the core to the version **4.x** because the app can't compile due to a lot of duplicate classes (coming from both the core versions **3.x** and **4.x**).

When will the drop-in SDK support  the version **4.x** of the core SDK?

**Comment by sshropshire** [comment]
HI @fondesa thanks for using the Braintree SDK for Android. We're working on releasing a beta version of DropIn that uses `v4` of the core Braintree SDK. We don't have a specific timeline, but we're doing some due diligence with testing, migrating to jetpack libraries, etc. We'll post here once we have an update.

**Comment by soarb** [comment]
Similar story for us. Our project uses the drop-in to let users manage their payment methods, but we provide a custom payment button with which we wish to 'upgrade' our payment method nonce to a 3DS 2 nonce. As we offer the App for both platforms, we've already achieved this with the ios drop-in and braintree core SDKs without any issue.

For Android, based on the guidelines here: https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/android/v4, the inclusion of the com.braintreepayments.api:three-d-secure:4.+ library immediately causes us build problems as it references v 4.x of the core SDK. I know there's "no specific timeline" on this but being based in the UK we're kind of going to have this enforced upon us by the 14th of September according to these FCA rules https://www.payments.service.gov.uk/3d-secure-2/

Would appreciate any advice anyone might have? Unless I've missed something of course! :)

**Comment by sarahkoop** [comment]
Hi @soarb - We do offer 3DS 2 in `v3` of the Braintree Android SDK that is compatible with the latest version of Drop-in. For now, we would recommend including `com.braintreepayments.api:three-d-secure:3.17.4` with Drop-in. For a guide to migrating to 3DS 2 with `v3` of the SDK, please see these [developer docs](https://developer.paypal.com/braintree/docs/guides/3d-secure/migration/android/v3).

**Comment by soarb** [comment]
@sarahkoop - oh I didn't realise! that's good thanks :) 

Just a little suggestion, would it be worth updating the docs here: https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/android/v4 - specifically the Custom UI section to say only add three-d-secure:4.x if not using the drop-in as well? Just whilst the drop-in is being migrated?

We only ended up in this boat as Apple rejected our previous drop-in only solution (I'm sure I've seen you in the related Github issue!) i.e., using the Apple Pay mark to display the Apple Pay Sheet ... now we use the drop-in to allow the customer to manage payment methods, but we now provide a custom UI button to perform the checkout so that it adheres to Apple's style guidelines. 

Of course we wanted to provide a consistent experience for Android users, and it's following the docs to include the 4.x three-d-secure:4.x library that got me into this mess in the first place!

Anyway, it's good to know 3DS2 is is already in com.braintreepayments.api:three-d-secure:3.17.4 - sorry if I didn't spot this first time round!

Thanks :)

**Comment by sarahkoop** [comment]
@soarb Thanks for the info - we will look into getting those docs updated 👍 ! In the meantime, we've released version `6.0.0-beta2` of the drop-in SDK that _is_ compatible with v4 of the core SDK modules. We welcome any feedback you have on the beta - leaving this issue open until we've released the GA version.

**Comment by sshropshire** [comment]
@Farbklex for the most part the beta is functionally complete. There are a few areas where we'd like to improve unit test coverage and there are a few classes that may be refactored/simplified in the process.

**Comment by sarahkoop** [comment]
Version `6.0.0` of the Drop-in SDK has been released, which is compatible with v4 of the Braintree Android SDK modules
