### ISSUE TITLE
support for older card.io libraries dropped?

### ISSUE THREAD

**Issue by jpage4500** [braintree/braintree-android-drop-in#30]
### General information

Our gradle setup:
```
    compile 'com.braintreepayments.api:braintree:2.4.2'                 // Braintree for handling payments
    compile 'com.braintreepayments.api:drop-in:3.0.6'                   // Built in "drop in" UI for braintree payment selections
```

```
    compile 'io.card:android-sdk:5.0.1'                                 // Card.IO - credit card scanning; NOTE: don't update past 5.0.1 as newer versions are much larger
```

Also, we include version 5.0.1 of io.card library. The reason we're using 5.0.1 was the size of this library ballooned on later version. See: https://github.com/card-io/card.io-Android-SDK/issues/178

### Issue

The latest version of the drop-in plugin doesn't seem to work anymore with card.io card scanning. At least previous versions did show a 'scan card' option in the 'add credit card' screen and it's not there anymore.

We see the button if we use the latest version of card.io library.. but, I'm not sure we'll be able to do this due to the added library size (it's already large enough on it's own)

**Comment by jpage4500** [comment]
I should have mentioned that the card scanning feature had worked just fine previously with older versions of the drop-down UI library

**Comment by lkorth** [comment]
The [README does point to using](https://github.com/braintree/braintree-android-drop-in#cardio) `compile 'io.card:android-sdk:[5.5.0,6.0.0)'`, mainly because it has been tested and 5.4.x [lacked support](https://github.com/card-io/card.io-Android-source/issues/100) for quite a few phones due to a processor architecture issue.

That said, I don't see any reason why it shouldn't work with older versions of card.io. Drop-in does not actually depend on card.io or directly interact with it at all, https://github.com/braintree/android-card-form handles the interaction with card.io so it may have happened in android-card-form 3.0.3 or 3.0.4.

If you run: 

```
new CardForm(context).isCardScanningAvailable();
```

in your app, does it return true, or false? Are there any card.io lines in your logcat?

**Comment by jpage4500** [comment]
I can try this and report back.

In the meantime, we did go back to using drop-in library version 3.0.5 and the scan card button is back. 

```
compile 'com.braintreepayments.api:drop-in:3.0.5'
```

But, it would be nice to upgrade to the latest eventually. I also wish there was a good solution for the card.io library too but I'm pretty sure it's too large to include in our app as-is..

**Comment by jpage4500** [comment]
sorry for the delay - I was wrong when I said going back to 3.0.5 fixed the issue. The scan button still isn't there and I think I know why. This log line turned me on to it:

```
W	card.io 	 - Error opening camera: java.lang.RuntimeException: Fail to connect to camera service
```

At some point in the last few months we updated our app to set the latest targetSdkVersion version which has the side-effect of requiring run-time permissions (https://developer.android.com/training/permissions/requesting.html)

So, devices running android 6.0+ won't grant permissions based on the AndroidManifest anymore but need to prompt the user. Older OS's should still work as they do today.

It might be a little awkward to fix this by prompting the user before we open the drop-in UI but I'll try that and see if it works. I suppose ideally the user would be prompted when the actually clicked on the 'scan card' button but I can see how that'd require some changes in the library.

**Comment by jpage4500** [comment]
note - i confirmed the 'scan card' button shows up if camera permission is requested before showing the drop-down UI.. it is fairly weird though since we have to do it for everyone regardless if they want to actually scan a card.

**Comment by lkorth** [comment]
Thanks for reporting back with your findings!

That makes sense, [card.io 5.1.0](https://github.com/card-io/card.io-Android-SDK/blob/c3fcd5e6b563aca8b87cbc7f4ff008a8bb4b46ef/CHANGELOG.md#510) was the first version to support runtime permissions and would be the minimum version to use if your target SDK version is 23+. Like you mentioned, the work around for this would be to request the camera permission before checking if card.io is supported and showing the scan icon. However that doesn't really work well with how runtime permissions are designed to be used right when a user wants to access a feature that requires the permission.

Unfortunately this issue has already been fixed in card.io 5.1.0 and newer so we will not be implementing a work around or change to `braintree-android-drop-in` or `android-card-form` to handle this case.
