### ISSUE TITLE
Deprecated DropInClient constructor with context parameter

### ISSUE THREAD

**Issue by Burtan** [braintree/braintree-android-drop-in#345]
### General information

* SDK/Library version: 6.1.0

### Issue description
Hey, the DropInClient constructor with context, token and dropInRequest has been deprecated. I wonder, what's the reason for that, now that with viewmodels and coroutines you don't really want callbacks anymore as you can just suspend your network thread. I'm have been creating the DropInClient in the viewmodel where I only have the appcontext available.

**Comment by sshropshire** [comment]
Hi @Burtan thanks for using the Braintree SDK for Android. Going forward, we want support the [Activity Result API](https://developer.android.com/training/basics/intents/result) for instances where an app switch occurs.

In the case of a process kill, a lifecycle-scoped pending coroutine will be cancelled while the user is completing an out-of-app payment flow. The listener pattern fits well here because even when a host `Activity` or `Fragment` is not the original DropIn launcher, we can still notify your app that a user is done with an out-of-app payment flow.

On the other hand, we are always looking for ways to improve the SDK and would like to support use cases like yours. Out of curiosity, how are you calling `launchDropInForResult()` from within your ViewModel? This method also requires an activity reference.

I'll also recommend you visit [this discussion](https://github.com/braintree/braintree_android/discussions/496) in our core repo about improving the developer experience. We're actively planning our next major version and we'd like to gather as much feedback as possible from the community on our API design.

**Comment by Burtan** [comment]
```
suspend fun prepareGiftPurchase(): DropInClient {
      return withContext(Dispatchers.IO) {
          val cc = DataCache.getCountry(true, appContext)
          val model = getModel(modelId)
          val token = api.v1PurchasesGet(cc).process().token
          val secureRequest = ThreeDSecureRequest()
          secureRequest.versionRequested = ThreeDSecureRequest.VERSION_2
          secureRequest.amount = model.getPrice(cc, PRICE_FULL).toPlainString()
          secureRequest.email = userSession.user.name

          val dropInRequest = DropInRequest()
          dropInRequest.threeDSecureRequest = secureRequest

          DropInClient(appContext, token, dropInRequest)
      }
  }
```

Im running launchDropInForResult in the ui class in the lifecycleScope after receiving the DropInClient in this suspending function. Beside requesting the token async, I'm also requerying the price from the server to make sure it's up-to-date and not an old cached one. So there is no value for me to let the Braintree SDK do the async part of the token request as I have to manage getting the price async anyway.

**Comment by sshropshire** [comment]
@Burtan got it yeah that makes sense. We do want to support your use case, the deprecation was mainly because that codepath uses `startActivity` internally, which is also deprecated.

In our next major version we will make an attempt to clean up the API to better fit the evolving Android ecosystem. Do you have a sort of "dream" interface for your use case that we could consider moving forward?

**Comment by Burtan** [comment]
I think it's fine as long as the following flow is possible:

Ui calls the viewModel via coroutine to prepare the purchase flow and suspends until it is ready. The prepared flow is returned and shown by the ui. The result is returned via Activity Result Api. Alternatively, if possible the result could also be returned directly via coroutine. So you don't have to handle the callback.

**Comment by sshropshire** [comment]
@Burtan my only concern would be in the case of a process kill. If the host activity / fragment is recreated, then it's the callers responsibility to invoke the `suspend` coroutine in `onCreate` or `onResume` to receive the result.

Since the payment flow is typically launched in response to a user interaction, it would require separate logic to determine if a pending result is available.

**Comment by Burtan** [comment]
I'm not sure how a process kill works here. If the app is closed gracefully then the coroutine is cancelled and the api should be able to cancel the purchase. The user just has to restart the payment flow if he still wants to do any purchase. If the app is not closed gracefully and the payment has just finished before the app has to call its paymentserver anyway to get updated data?

**Comment by crazylotus** [comment]
val dropInRequest = DropInRequest()
        dropInRequest.threeDSecureRequest = commonMethods.threeDSecureRequest(payableWalletAmount)
        dropInRequest.threeDSecureRequest = commonMethods.threeDSecureRequest(payableWalletAmount)
        val dropInClient =  DropInClient(this, sessionManager.brainTreeClientToken, dropInRequest)
        dropInClient.launchDropInForResult(this, REQUEST_CODE)
        
        DropInClient constructor and startActivity both are deprecated... Is there any alternative or any update @sshropshire

**Comment by sshropshire** [comment]
@crazylotus can you elaborate more on what you're requesting?

The docs highlight our [recommended integration pattern](https://developer.paypal.com/braintree/docs/guides/drop-in/setup-and-integration/android/v4). Is there another way that's more optimal for your app?

**Comment by sarahkoop** [comment]
Hi @crazylotus - I'm going to close this issue now due to inactivity - but please open a new issue or GitHub discussion if you have suggestions for API improvements!
