### ISSUE TITLE
Disappearing title "Select Payment Method"

### ISSUE THREAD

**Issue by hellmund** [braintree/braintree-android-drop-in#62]
### General information

* SDK/Library version: 3.1.0
* Environment: Sandbox and Production
* Android Version and Device: 7.0, Samsung Galaxy S8

### Issue description

Opening the payment method selection shows the title "Select Payment Method". When having one vaulted payment method, that title is only briefly visible and disappears on Android.

Expected behavior: Title should remain visible to make interaction with payment methods clear to user. In the iOS implementation this is the case.

**title "Select Payment Method" briefly visible:**
![android_title1](https://user-images.githubusercontent.com/4047559/35563843-5e938536-05b8-11e8-84e7-a8ee7d000c60.png)

**title "Select Payment Method" disappeared**
![android_title2](https://user-images.githubusercontent.com/4047559/35563853-662d1154-05b8-11e8-95a1-4b25aecdfc18.png)

In the iOS version of the Braintree Drop-in UI, the title remains visible.

**Braintree Drop-in UI on iOS with title permanently visible**
![ios_title](https://user-images.githubusercontent.com/4047559/35563823-48fbb73e-05b8-11e8-822a-7edec4914739.jpg)

**Comment by sdcoffey** [comment]
Hey @hellmund,

Thanks for the feedback. This is actually expected behavior. Even though these UI elements are roughly equivalent across platforms, they're designed to look and feel slightly differently, and this is one of those difference. Please feel free to open another issue if you discover other issues in Drop-in!
