### ISSUE TITLE
Google pay sandbox

### ISSUE THREAD

**Issue by er-nishka** [braintree/braintree-android-drop-in#65]
I'm not able to implement google pay with sandbox environment.  Can you please show me how to implement it. I search the whole document of braintree drop in ui with google pay but wasn't able to find how to set sandbox environment.
Please do the needful.

**Comment by jaypatel512** [comment]
Hey @er-nishka !

I think [this documentation](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v2) would help you to get started with DropIn on Android. For enabling Google Pay in Android, you need to follow the steps mentioned [here](https://developers.braintreepayments.com/guides/android-pay/overview).

Let us know if you have any specific question about the integration.

**Comment by sdcoffey** [comment]
Hey @er-nishka,

We don't have any docs specifically on Google Pay and Drop-in, but the integration is just a combination of the two. First, refer to the [instructions for starting Drop-in on Android](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v2#starting-drop-in).

What you're going to do is create a `GooglePaymentRequest` as documented in our [Google Pay docs](https://developers.braintreepayments.com/guides/google-pay/client-side/android/v2#braintree-sdk-integration), and attach that to your request object. The code should look something like the following:

```java
private void startDropinWithGooglePay() {
    GooglePaymentRequest googlePaymentRequest = new GooglePaymentRequest()
                .transactionInfo(TransactionInfo.newBuilder()
                        .setTotalPrice("1.00")
                        .setCurrencyCode("USD")
                        .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
                        .build())
                .emailRequired(true);

    DropInRequest dropInRequest = new DropInRequest()
      .clientToken(CLIENT_TOKEN)
      .googlePaymentRequest(googlePaymentRequest); 

    startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE);
}
```

Please feel free to open another issue if you find a bug in Drop-in, otherwise plese refer to our [support resources](https://articles.braintreepayments.com) if you have questions about integration steps.
