### ISSUE TITLE
Drop in ui not showing

### ISSUE THREAD

**Issue by jin9393** [braintree/braintree-android-drop-in#7]
I used async to fetch token from my server and at the end of the async i call the dropin function and nothing happen after that. However, when i hard coded the token into a string and place it into the dropin function the ui appear. Any way to solve this?

**Comment by quinnjn** [comment]
It sounds like fetching the token from the server is the issue since Drop-in launches fine with a hard coded client token.

You can verify your client token is correct by following these steps:

When Drop-in is [passed a malformed authorization it finishes with an error](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInActivity.java#L105-L107). 

This [example usage](https://github.com/braintree/braintree-android-drop-in/blob/937ce6ef1981776e0e4717537ed58de43bc1b298/README.md#usage) in our README shows where that error is referenced back to your activity.

That exception will clue into why Drop-in is not starting.

**Comment by quinnjn** [comment]
@jin9393 I'm going to close this. Feel free to reopen it if you are still having issues.

**Comment by jin9393** [comment]
Sorry I forget I posted here as i have been on email with braintree support team. Yes i am still facing the same error since that day.

onActivityResult, i cant cast data to exception. The drop-in ui is still not loading. I have sent over the whole code to the support team and still waiting for their feedback.

**Comment by quinnjn** [comment]
You shouldn't cast `Intent data` to an `Exception`. See our [Usage](https://github.com/braintree/braintree-android-drop-in#usage) example.

If some serializable extra exists under `DropInActivity.EXTRA_ERROR` then the exception will be there.

**Comment by jin9393** [comment]
My bad, I did exactly what is stated on the example and i got this when i try to log the exception.
"Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Exception".

**Comment by jin9393** [comment]
Another thing to take note is the onActivityResult resultCode. The resultCode is returning 1 and its not loading into resultCode == Activity.RESULT_OK, even though the drop-in is not loading

**Comment by quinnjn** [comment]
> when i try to log the exception.
"Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Exception"

Hmm, we do pass a string as a value for `DropInActivity.EXTRA_ERROR` when [BraintreeFragment has an invalid argument](https://github.com/braintree/braintree-android-drop-in/blob/4e6de317525b0d6299bbe7afb071b982b48e57d9/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInActivity.java#L105-L107) which sounds like it would be the Client Token mentioned in your first comment. We should be passing the Exception back and not the String though so we'll work on a fix for that! This would be unrelated to the invalid argument that is being passed in though.

> resultCode is returning 1 and its not loading into resultCode == Activity.RESULT_OK, even though the drop-in is not loading

This makes sense, [`Activity.RESULT_OK == -1`](https://developer.android.com/reference/android/app/Activity.html#RESULT_OK). `RESULT_OK` would be used when Drop-in finishes successfully. If it has an issue it would not return `RESULT_OK` [`Activity.RESULT_FIRST_USER == 1`](https://developer.android.com/reference/android/app/Activity.html#RESULT_FIRST_USER) which is the value we use to represent that an [error has happened when using Drop-in](https://github.com/braintree/braintree-android-drop-in/blob/4e6de317525b0d6299bbe7afb071b982b48e57d9/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInActivity.java#L107).

Please check the value you're getting back for `DropInActivity.EXTRA_ERROR`. If the error is `Tokenization Key or client token was invalid` we will know that the client token is malformed, and there is some issue with passing the String from your server.

**Comment by jin9393** [comment]
Yes client token was invalid. Thing have been solved. The token from the server pass in with a extra double quote and it was insert into the drop-in ui token. Was solved after removing it. Thanks you very much
