### ISSUE TITLE
Braintree drop-in-ui appium automation issue

### ISSUE THREAD

**Issue by kadir-calvid** [braintree/braintree-android-drop-in#83]
### General information

* SDK/Library version: 2.2
* Environment:  Sandbox 
* Android Version and Device: lenovo tab3 essential with Android 5.1.0 
* Appium: 1.8.2
 * node: 1.8.2

### Issue description
Hello,
I want to do appium automation for Braintree drop-in-ui  but unable to inspect the elements to automate
is there any way to inspect elements for find there ids or class name
Any suggestion and solution would be appreciated

Thank
kadir khan

**Comment by jackellenberger** [comment]
Hi @kadir-calvid, for our testing we generally search on visible strings rather than Id's to avoid problems that come up with the elements not being ready when the test framework starts up. Perhaps you could try something similar? [Here is an example](https://github.com/braintree/braintree_android/blob/master/Demo/src/androidTest/java/com/braintreepayments/demo/test/DropInTest.java#L69) of a bit of testing that we do for our demo app. We're not using Appium, but the theory may still apply.

Give that a try and tell us how it goes!

**Comment by kadir-calvid** [comment]
@jackellenberger Thanks jack.
I have tried with visible strings only but its working for "Card Number",
But not for "Expiration Date" and "CVV" number.

Thanks
kadir khan
