### ISSUE TITLE
build fail can't find dependency card-form 3.4.1

### ISSUE THREAD

**Issue by bethucbg** [braintree/braintree-android-drop-in#88]
I have been upgrade drop in version 3.5.2
but can't build success. Anyone can help ?
Thanks.

**Comment by crookedneighbor** [comment]
Can you provide more information about how it's failing? A stacktrace?

**Comment by quinnjn** [comment]
I know there was an issue with jcenter not mirroring maven releases last week. We had an [issue in braintree_android](https://github.com/braintree/braintree_android/issues/229#issuecomment-417396518) reported. 

It would make sense for android-card-form to also be delayed by jcenter since 3.4.1 was released around the time of the issue.

Closing this since jcenter has resolved it. Comment if the issue still persists.
