### ISSUE TITLE
Venmo payment method is not vaulted

### ISSUE THREAD

**Issue by coolbeet** [braintree/braintree-android-drop-in#98]
### General information

* SDK/Library version: 3.7
* Environment: both Sandbox and Production? 
* Android Version and Device: doesn't matter

### Issue description
After the user selects and authorizes Venmo as the payment method, the payment nonce is successfully fetched and can be used for creating a transaction, but it does not get saved in the vault automatically like iOS.

Thanks!

**Comment by crookedneighbor** [comment]
We'll take a look. Thanks for the report!

**Comment by crookedneighbor** [comment]
I think the problem may actually be on the iOS side, in that it should not be auto-vaulting the venmo account. 

See this bit in the JS Drop-in documentation https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#venmo

> If using a client token with a customer id, the Venmo account will not automatically be vaulted. You can use the payment method nonce to create a payment method on your server.

This is because Vaulted venmo accounts can be used as part of a subscription service (where the charge is recurring and identical) or as part of a split payment transaction, but not as a normal vaulted payment method.

We'll check into iOS's behavior and get back to you.

**Comment by scannillo** [comment]
On iOS Drop-In [v8.1.0,](https://github.com/braintree/braintree-ios-drop-in/blob/master/CHANGELOG.md#810-2020-04-01) you can opt in or out of Venmo vaulting with the `vaultVenmo` flag on the `BTDropInRequest`.

In Android Drop-In, it looks like vaulting Venmo at all is not currently supported. See the code snippet for the [`Venmo#authorizeAccount`](https://github.com/braintree/braintree_android/blob/c4df79544f92b8966e47bdc92fe0285982edd00b/Braintree/src/main/java/com/braintreepayments/api/Venmo.java#L100-L114) method and then Drop-In's use of it [here](https://github.com/braintree/braintree-android-drop-in/blob/15eb972c5e0b8ee2718f567f2821206c4a3674b7/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInActivity.java#L267-L269).

We will add this to work our roadmap and leave this issue open for tracking/updates.

**Comment by sarahkoop** [comment]
Hi @coolbeet - The option to vault Venmo has been added in `v5.0.0`.  You can opt in to Venmo vaulting by setting the `vaultVenmo` flag to `true` on `DropInRequest`.
